version: 0.2

phases:
  install: 
    runtime-versions:
      php: 7.3
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    # login to Elastic container registryssd
    - eval $(aws ecr get-login --region us-east-1 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=240066087291.dkr.ecr.us-east-1.amazonaws.com/intercambiokbt
    - IMAGE_TAG=latest
  build:
    commands:
    - echo Build started on `date`
    - echo installing composer..
    - composer install
    - docker build -t intercambiokbt .
    - docker tag intercambiokbt:latest 240066087291.dkr.ecr.us-east-1.amazonaws.com/intercambiokbt:latest   
  post_build:
    commands:
    - docker push $REPOSITORY_URI:$IMAGE_TAG 